#ifndef MWA_CONFIG_H
#define MWA_CONFIG_H
/////////////// MICROWIRE   ARRAY CONFIG

#define MAX_NUM_OF_MWA				2
#define MAX_NUM_OF_CHAN_PER_MWA	16
#define MAX_NUM_OF_UNIT_PER_CHAN	4

#define NUM_OF_MWA_NULL				MAX_NUM_OF_MWA
#define NUM_OF_CHAN_PER_MWA_NULL	MAX_NUM_OF_CHAN_PER_MWA



#endif
