#ifndef NETWORK_CONFIG_H
#define NETWORK_CONFIG_H


#define LAYER_BASE_SERVO_EXTENSOR_SPINY 			0		//   decreasing pulse width for servo)   ///  TURN TO RIGHT
#define LAYER_BASE_SERVO_FLEXOR_SPINY				1		//   incresing pulse width for servo)   ///  TURN TO LEFT
#define LAYER_SUPERFLUOUS								2		//   incresing pulse width for servo)   ///  TURN TO LEFT

#define NUM_OF_IN_SILICO_NETWORK_LAYERS 				3	

#define NUM_OF_OUTPUT_SPINY_PROJECTION_NEURONS 	1	
#define NUM_OF_SUPERFLUOUS_NEURONS 				150


#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_WEIGHT_MAX				6.0
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_WEIGHT_MIN				6.0
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_DELAY_MIN					3000000
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_DELAY_MAX					BLUESPIKE_2_IN_SILICO_EXCITATORY_DELAY_MIN+2000000


#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_WEIGHT_MAX					12.0
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_WEIGHT_MIN					12.0
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_DELAY_MIN					3000000
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_DELAY_MAX					BLUESPIKE_2_IN_SILICO_INHIBITORY_DELAY_MIN+2000000


#define	BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_PROBABILITY				0.66
#define	BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_WEIGHT_MAX				6.0
#define	BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_WEIGHT_MIN				6.0
#define	BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_DELAY_MIN				3000000
#define	BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_DELAY_MAX				BLUESPIKE_2_SUPERFLUOUS_EXCITATORY_DELAY_MIN+2000000

#define	BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_PROBABILITY				0.0
#define	BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_WEIGHT_MAX				12.0
#define	BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_WEIGHT_MIN				12.0
#define	BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_DELAY_MIN					3000000
#define	BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_DELAY_MAX					BLUESPIKE_2_SUPERFLUOUS_INHIBITORY_DELAY_MIN+2000000


#define	MSN_2_MSN_EXCITATORY_PROBABILITY					0.0
#define	MSN_2_MSN_EXCITATORY_WEIGHT_MAX					6.0
#define	MSN_2_MSN_EXCITATORY_WEIGHT_MIN					6.0
#define	MSN_2_MSN_EXCITATORY_DELAY_MIN					3500000
#define	MSN_2_MSN_EXCITATORY_DELAY_MAX					MSN_2_MSN_EXCITATORY_DELAY_MIN+2000000


#define	MSN_2_MSN_INHIBITORY_PROBABILITY					1.0
#define	MSN_2_MSN_INHIBITORY_WEIGHT_MAX					40.0
#define	MSN_2_MSN_INHIBITORY_WEIGHT_MIN					40.0
#define	MSN_2_MSN_INHIBITORY_DELAY_MIN						3500000
#define	MSN_2_MSN_INHIBITORY_DELAY_MAX						MSN_2_MSN_INHIBITORY_DELAY_MIN+2000000


#define	SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_PROBABILITY					0.0
#define	SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_WEIGHT_MAX					6.0
#define	SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_WEIGHT_MIN					6.0
#define	SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_DELAY_MIN					3500000
#define	SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_DELAY_MAX				SUPERFLUOUS_2_SUPERFLUOUS_EXCITATORY_DELAY_MIN+2000000

#define	SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_PROBABILITY					0.2
#define	SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_WEIGHT_MAX					0.3
#define	SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_WEIGHT_MIN						0.3
#define	SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_DELAY_MIN						3500000
#define	SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_DELAY_MAX						SUPERFLUOUS_2_SUPERFLUOUS_INHIBITORY_DELAY_MIN+2000000


#endif
