#ifndef INTER_PROCESS_MSG_CONFIG_H
#define INTER_PROCESS_MSG_CONFIG_H




#define NUM_OF_MOV_OBJ_HAND_2_NEURAL_NET_MSG_BUFFERS	IZ_PS_NETWORK_SIM_NUM_OF_DEDICATED_CPUS*MAX_NUM_OF_CPU_THREADS_PER_CPU

#define MIN_MOV_OBJ_HAND_2_NEURAL_NET_EVENT_SCHEDULING_DELAY MOV_OBJ_HANDLER_PERIOD + IZ_PS_NETWORK_SIM_PERIOD + 1000000 // 1 MS jitter buffer
//  MESSAGES FROM MOV OBJ HANDLER TO NEURAL NET


#define NUM_OF_NEURAL_NET_2_MOV_OBJ_HAND_MSG_BUFFERS 		IZ_PS_NETWORK_SIM_NUM_OF_DEDICATED_CPUS*MAX_NUM_OF_CPU_THREADS_PER_CPU

#define MIN_NEURAL_NET_2_MOV_OBJ_HAND_EVENT_SCHEDULING_DELAY MOV_OBJ_HANDLER_PERIOD + IZ_PS_NETWORK_SIM_PERIOD + 1000000 // 1 MS jitter buffer



#endif
