#ifndef INTER_PROCESS_MSG_CONFIG_H
#define INTER_PROCESS_MSG_CONFIG_H




#define MIN_MOV_OBJ_HAND_2_NEURAL_NET_EVENT_SCHEDULING_DELAY MOV_OBJ_HANDLER_PERIOD + SNN_SIM_PERIOD + 1000000 // 1 MS jitter buffer
//  MESSAGES FROM MOV OBJ HANDLER TO NEURAL NET


#define MIN_NEURAL_NET_2_MOV_OBJ_HAND_EVENT_SCHEDULING_DELAY MOV_OBJ_HANDLER_PERIOD + SNN_SIM_PERIOD + 1000000 // 1 MS jitter buffer



#endif
