#ifndef NETWORK_CONFIG_H
#define NETWORK_CONFIG_H


#define LAYER_BASE_SERVO_EXTENSOR_SPINY 			0		//   decreasing pulse width for servo)   ///  TURN TO RIGHT
#define LAYER_BASE_SERVO_FLEXOR_SPINY				1		//   incresing pulse width for servo)   ///  TURN TO LEFT

#define NUM_OF_IN_SILICO_NETWORK_LAYERS 				2	

#define NUM_OF_OUTPUT_SPINY_PROJECTION_NEURONS 	1	



#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_WEIGHT_MAX				6.0
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_WEIGHT_MIN				6.0
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_DELAY_MAX					MINIMUM_BLUE_SPIKE_TO_IN_SILICO_AXONAL_DELAY
#define	BLUESPIKE_2_IN_SILICO_EXCITATORY_DELAY_MIN					MINIMUM_BLUE_SPIKE_TO_IN_SILICO_AXONAL_DELAY

#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_WEIGHT_MAX					12.0
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_WEIGHT_MIN					12.0
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_DELAY_MAX					MINIMUM_BLUE_SPIKE_TO_IN_SILICO_AXONAL_DELAY
#define	BLUESPIKE_2_IN_SILICO_INHIBITORY_DELAY_MIN					MINIMUM_BLUE_SPIKE_TO_IN_SILICO_AXONAL_DELAY

#define	MSN_2_MSN_EXCITATORY_PROBABILITY					0.0
#define	MSN_2_MSN_EXCITATORY_WEIGHT_MAX					6.0
#define	MSN_2_MSN_EXCITATORY_WEIGHT_MIN					6.0
#define	MSN_2_MSN_EXCITATORY_DELAY_MAX					MINIMUM_IN_SILICO_TO_IN_SILICO_AXONAL_DELAY
#define	MSN_2_MSN_EXCITATORY_DELAY_MIN					MINIMUM_IN_SILICO_TO_IN_SILICO_AXONAL_DELAY

#define	MSN_2_MSN_INHIBITORY_PROBABILITY					1.0
#define	MSN_2_MSN_INHIBITORY_WEIGHT_MAX					40.0
#define	MSN_2_MSN_INHIBITORY_WEIGHT_MIN					40.0
#define	MSN_2_MSN_INHIBITORY_DELAY_MAX						MINIMUM_IN_SILICO_TO_IN_SILICO_AXONAL_DELAY
#define	MSN_2_MSN_INHIBITORY_DELAY_MIN						MINIMUM_IN_SILICO_TO_IN_SILICO_AXONAL_DELAY


#endif
